import{a as v,S as P,i as c}from"./assets/vendor-LK6CqzKq.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const b="https://pixabay.com/api/",B="51403158-2e3095c4822824a544700ea8f",E=15;async function u(i,r){const o={key:B,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:E};try{return(await v.get(b,{params:o})).data}catch(n){throw console.error("❌ Pixabay request error:",n),n}}const p=document.querySelector(".gallery"),f=document.querySelector(".loader"),h=document.querySelector(".load-more"),M=new P(".gallery a");function m(i){const r=i.map(({webformatURL:o,largeImageURL:n,tags:e,likes:t,views:a,comments:S,downloads:q})=>`
        <li class="gallery-item">
          <a href="${n}">
            <img src="${o}" alt="${e}" />
          </a>
          <div class="info">
            <p>👍 ${t}</p>
            <p>👁️ ${a}</p>
            <p>💬 ${S}</p>
            <p>⬇️ ${q}</p>
          </div>
        </li>
      `).join("");p.insertAdjacentHTML("beforeend",r),M.refresh()}function R(){p.innerHTML=""}function g(){f.classList.remove("is-hidden")}function y(){f.classList.add("is-hidden")}function $(){h.classList.remove("hidden")}function L(){h.classList.add("hidden")}const w=document.querySelector(".form"),O=w.querySelector('input[name="search-text"]'),x=document.querySelector(".load-more");let l="",s=1,d=0;w.addEventListener("submit",async i=>{if(i.preventDefault(),l=O.value.trim(),l===""){c.warning({message:"Please enter a search term!",position:"topRight"});return}R(),L(),g(),s=1;try{const r=await u(l,s),{hits:o,totalHits:n}=r;if(o.length===0){c.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m(o),d=Math.ceil(n/40),s<d&&$()}catch{c.error({message:"Oops! Something went wrong. Please try again later.",position:"topRight"})}finally{y()}});x.addEventListener("click",async()=>{s+=1,g();try{const i=await u(l,s),{hits:r}=i;m(r),s>=d&&(L(),c.info({message:"You've reached the end of search results.",position:"topRight"}));const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}catch{c.error({message:"Failed to load more images.",position:"topRight"})}finally{y()}});
//# sourceMappingURL=index.js.map
